# Generated by Django 3.1.3 on 2020-11-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izziapp', '0002_auto_20201119_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_order',
            new_name='date_register',
        ),
    ]
